kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: mem-elasticsearch-scc
  annotations:
    kubernetes.io/description: mem-elasticsearch-scc provides all features of the restricted SCC but allows users to run with any UID and any GID.
priority: 10
allowPrivilegedContainer: true
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostNetwork: false
allowHostPorts: false
allowHostPID: false
allowHostIPC: false
readOnlyRootFilesystem: false
allowedCapabilities: [
]
defaultAddCapabilities: [
]
requiredDropCapabilities: [
  ALL
]
runAsUser:
  type: RunAsAny
  # type: MustRunAs
  # runAsUser: 1000
fsGroup:
  type: RunAsAny
  # type: MustRunAs
  # ranges: [
  #   min: 1000,  # Use the minimum value of the first range as the default.
  #   max: 1100
  # ]
supplementalGroups:
  type: RunAsAny
  # type: MustRunAs
  # ranges: [
  #   min: 1000,  # Use the minimum value of the first range as the default.
  #   max: 1100
  # ]
seLinuxContext:
  type: MustRunAs
# The users and groups fields on the SCC control which users can access the SCC. All authenticated
# users are granted access to the Restricted SCC.
# system:serviceaccount:<serviceaccount_namespace>:<serviceaccount_name>
users: [
  system:serviceaccount:memories:mem-elasticsearch-master-service-account,
  system:serviceaccount:memories:mem-elasticsearch-data-service-account
]
groups: [
  system:authenticated
]
# For backwards compatibility, the usage of allowHostDirVolumePlugin overrides settings in the
# volumes field.
volumes: [
  configMap,
  downwardAPI,
  emptyDir,
  persistentVolumeClaim,
  projected,
  secret
]
