# To configure Filebeat, edit the configuration file. The default configuration file is called
# filebeat.yml.
# -------------------------------------------------------------------------------------------------
# For more available modules and options, please see the filebeat.reference.yml
# (https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-reference-yml.html) sample
# configuration file.
# =================================== Modules configuration =======================================
# filebeat.modules:
# ------------------------------------- Elasticsearch Module --------------------------------------
# - module: elasticsearch
  # Server log
  # server:
  #   enabled: true
    # Set custom paths for the log files. If left empty, Filebeat will choose the paths depending
    # on your OS.
    # var.paths:
  # gc:
  #   enabled: true
    # Set custom paths for the log files. If left empty, Filebeat will choose the paths depending
    # on your OS.
    # var.paths:
  # audit:
  #   enabled: true
    # Set custom paths for the log files. If left empty, Filebeat will choose the paths depending
    # on your OS.
    # var.paths:
  # slowlog:
  #   enabled: true
    # Set custom paths for the log files. If left empty, Filebeat will choose the paths depending
    # on your OS.
    # var.paths:
  # deprecation:
  #   enabled: true
    # Set custom paths for the log files. If left empty, Filebeat will choose the paths depending
    # on your OS.
    # var.paths:
# ---------------------------------------- Kibana Module ------------------------------------------
# - module: kibana
#   # Server logs
#   log:
#     enabled: true
#     # Set custom paths for the log files. If left empty, Filebeat will choose the paths depending
#     # on your OS.
#     # var.paths:
#   # Audit logs
#   audit:
#     enabled: true
#     # Set custom paths for the log files. If left empty, Filebeat will choose the paths depending
#     # on your OS.
#     # var.paths:
# ====================================== Filebeat Inputs ==========================================
# To configure inputs:
#   https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html
# Inputs specify how Filebeat locates and processes input data.
filebeat.inputs:
  # Read containers log files.
  - type: container
    # Change to true to enable this input configuration.
    enabled: true
    # Read from the specified streams only: all (default), stdout or stderr.
    stream: all
    # Use the given format when reading the log file: auto, docker or cri. The default is auto; it
    # will automatically detect the format.
    format: auto
    encoding: utf-8
    # To collect container logs, each Filebeat instance needs access to the local log's path, which
    # is actually a log directory mounted from the host. With this configuration, Filebeat can
    # collect logs from all the files that exist under the /var/log/containers/ directory.
    paths:
      - '/var/log/containers/*.log'
    # Filebeat exports only the lines that match a regular expression in the list. By default, all
    # lines are exported. Empty lines are ignored.
    # include_lines: ['^ERR', '^WARN', '^INFO']
    # exclude_lines: ['^DBG']
    fields_under_root: true
    fields:
      # To be used by Logstash for distinguishing index names while writing to Elasticsearch.
      index_prefix: k8s-logs-memories
    # Enrich events with k8s, cloud metadata.
    processors:
      - add_kubernetes_metadata:
          in_cluster: true
          host: $(NODE_NAME)
          matchers:
            - logs_path:
                logs_path: '/var/log/containers/'
    # logging:
    #   # Available log levels are: critical, error, warning, info (default), debug.
    #   # Set logging.level to debug to see the generated events by the running filebeat instance.
    #   # level: info
    #   level: debug
    #   # At debug level, you can selectively enable logging only for some components. To enable all
    #   # selectors use ["*"]. Examples of other selectors are "beat", "publish", "service".
    #   selectors: ["publish"]
    #   to_files: true
    #   to_syslog: false
    #   files:
    #     path: '/var/log/my_filebeat'
    #     name: my_filebeat.log
    #     keepfiles: 7
    #     permissions: 0660
# ========================================== Processors ===========================================
processors:
  - add_cloud_metadata: ~
  - add_host_metadata: ~
# ============================================ Outputs ============================================
# Configure what output to use when sending the data collected by the beat. Only a single output
# may be defined.
# See https://www.elastic.co/guide/en/beats/filebeat/current/configuring-output.html
output.logstash:
  enabled: false
  protocol: 'http'
  # The Logstash hosts.
  hosts: ['mem-logstash.memories.svc.cluster.local:5044']
  # Configure escaping HTML symbols in strings.
  escape_html: true
  # Number of workers per Logstash host.
  worker: 1
  loadbalance: false
  ttl: 0
  pipelining: 2
output.elasticsearch:
  enabled: true
  protocol: 'http'
  # The Logstash hosts.
  hosts: ['mem-elasticsearch-client.memories.svc.cluster.local:9200']
  ssl.enabled: false
# Filebeat comes packaged with example Kibana dashboards, visualizations, and searches for
# visualizing Filebeat data in Kibana. If Kibana is not available at startup, Filebeat will stop
# with an error.
# See https://www.elastic.co/guide/en/beats/filebeat/current/configuration-dashboards.html
setup.dashboards:
  enabled: true
  beat: "filebeat"
  # The name of the Kibana index to use for setting the configuration.
  kibana_index: ".kibana-memories"
  index: "memories-*"
  always_kibana: true
  retry.enabled: true
  retry.interval: 3  # In seconds.
  retry.maximum: 3
# See https://www.elastic.co/guide/en/beats/filebeat/current/setup-kibana-endpoint.html
setup.kibana:
  enabled: true
  protocol: 'http'
  host: 'mem-kibana.memories.svc.cluster.local:5601'
  path: '/kibana'
  ssl.enabled: false
  ssl.verification_mode: 'none'
setup.template:
  enabled: true
  settings:
    index.number_of_shards: 2
